{% set name = "gcloud-aio-datastore" %}
{% set version = "7.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: de17d687c6bfea93a9d1dab00d4c2b0533e7d5388c04bdc3591461270fc5bccd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<4.0
    - gcloud-aio-auth >=3.1.0,<5.0.0
    - setuptools >=66.0.0,<67.0.0

test:
  imports:
    - gcloud.aio.datastore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Datastore
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
