schema_version: 1

context:
  name: gcloud-aio-datastore
  version: "9.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gcloud_aio_datastore-${{ version }}.tar.gz
  sha256: 7b8b6fdf0679f7535f4e0f1b58a7dfdc9ec09ab8c68c6a57b5611359c8900309

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - gcloud-aio-auth >=3.1.0,<6.0.0

tests:
  - python:
      imports:
        - gcloud.aio.datastore
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python Client for Google Cloud Datastore
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/talkiq/gcloud-aio

extra:
  recipe-maintainers:
    - xylar
